## Importação das bibliotecas

In [83]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px

In [84]:
data = pd.read_csv('Heart Failure Clinical Records.csv')
data.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

## Análise exploratória

In [85]:
print('Tamanho: ', end="")
print(data.shape)
print('-----------------------------------------------------------------------------------------------------------')
display(data.describe())
print('-----------------------------------------------------------------------------------------------------------')
print(data.info())

Tamanho: (299, 13)
-----------------------------------------------------------------------------------------------------------


age     anaemia  creatinine_phosphokinase    diabetes  \
count  299.000000  299.000000                299.000000  299.000000   
mean    60.833893    0.431438                581.839465    0.418060   
std     11.894809    0.496107                970.287881    0.494067   
min     40.000000    0.000000                 23.000000    0.000000   
25%     51.000000    0.000000                116.500000    0.000000   
50%     60.000000    0.000000                250.000000    0.000000   
75%     70.000000    1.000000                582.000000    1.000000   
max     95.000000    1.000000               7861.000000    1.000000   

       ejection_fraction  high_blood_pressure      platelets  \
count         299.000000           299.000000     299.000000   
mean           38.083612             0.351171  263358.029264   
std            11.834841             0.478136   97804.236869   
min            14.000000             0.000000   25100.000000   
25%            30.000000             0.000000  212500.000000   
50%            38.000000             0.000000  262000.000000   
75%            45.000000             1.000000  303500.000000   
max            80.000000             1.000000  850000.000000   

       serum_creatinine  serum_sodium         sex    smoking        time  \
count         299.00000    299.000000  299.000000  299.00000  299.000000   
mean            1.39388    136.625418    0.648829    0.32107  130.260870   
std             1.03451      4.412477    0.478136    0.46767   77.614208   
min             0.50000    113.000000    0.000000    0.00000    4.000000   
25%             0.90000    134.000000    0.000000    0.00000   73.000000   
50%             1.10000    137.000000    1.000000    0.00000  115.000000   
75%             1.40000    140.000000    1.000000    1.00000  203.000000   
max             9.40000    148.000000    1.000000    1.00000  285.000000   

       DEATH_EVENT  
count    299.00000  
mean       0.32107  
std        0.46767  
min        0.00000  
25%        0.00000  
50%        0.00000  
75%        1.00000  
max        1.00000

-----------------------------------------------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64  
 2   creatinine_phosphokinase  299 non-null    int64  
 3   diabetes                  299 non-null    int64  
 4   ejection_fraction         299 non-null    int64  
 5   high_blood_pressure       299 non-null    int64  
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64  
 9   sex                       299 non-null    int64  
 10  smoking                   299 non-null    int64  
 11  time                      299 non-null    int64  
 12  DEATH_EVENT 

Aqui observamos que temos mais mulheres do que homens na nossa base de dados.

In [86]:
tmp = data.copy()
tmp['sex'] = tmp['sex'].apply(lambda x: 'Mulher' if x == 0 else 'Homem')
tmp['DEATH_EVENT'] = tmp['DEATH_EVENT'].apply(lambda x: 'Não faleceu' if x == 0 else 'Faleceu')

fig = px.pie(tmp, names='sex', width=500, color_discrete_sequence=['#19647E', '#A31621'])
fig.update_xaxes(title_text='Sexo')
fig.update_yaxes(title_text='')
fig.update_layout(bargap=0.2)
# fig.show()
display(data)


age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    75.0        0                       582         0                 20   
1    55.0        0                      7861         0                 38   
2    65.0        0                       146         0                 20   
3    50.0        1                       111         0                 20   
4    65.0        1                       160         1                 20   
..    ...      ...                       ...       ...                ...   
294  62.0        0                        61         1                 38   
295  55.0        0                      1820         0                 38   
296  45.0        0                      2060         1                 60   
297  45.0        0                      2413         0                 38   
298  50.0        0                       196         0                 45   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                      1  265000.00               1.9           130    1   
1                      0  263358.03               1.1           136    1   
2                      0  162000.00               1.3           129    1   
3                      0  210000.00               1.9           137    1   
4                      0  327000.00               2.7           116    0   
..                   ...        ...               ...           ...  ...   
294                    1  155000.00               1.1           143    1   
295                    0  270000.00               1.2           139    0   
296                    0  742000.00               0.8           138    0   
297                    0  140000.00               1.4           140    1   
298                    0  395000.00               1.6           136    1   

     smoking  time  DEATH_EVENT  
0          0     4            1  
1          0     6            1  
2          1     7            1  
3          0     7            1  
4          0     8            1  
..       ...   ...          ...  
294        1   270            0  
295        0   271            0  
296        0   278            0  
297        1   280            0  
298        1   285            0  

[299 rows x 13 columns]

Aqui podemos ver que apenas 32% dos homens e 32,4% das mulheres da base de dados faleceram durante o acompanhamento

In [87]:
fig = px.histogram(tmp, x='DEATH_EVENT', width=500, 
             color_discrete_sequence=['#19647E', '#A31621'], color='sex', labels={"sex": "Sexo"})
fig.update_xaxes(title_text='Evento')
fig.update_yaxes(title_text='')
fig.update_layout(bargap=0.2)
fig.show()

Aqui podemos observar que, dos pacientes falecidos, os homens são os que mais acabaram morrendo durante o acompanhamento

In [88]:
graph_df = tmp.loc[tmp['DEATH_EVENT'] == 'Faleceu']
fig = px.pie(graph_df, names='sex', width=500, 
             color_discrete_sequence=['#19647E', '#A31621'])
fig.show()

## Procurando features

In [89]:
corr = data.corr()
corr.style.background_gradient(cmap='coolwarm')

## Iniciando modelagem

In [90]:
from sklearn.model_selection import train_test_split

X = data[['time', 'serum_creatinine', 'ejection_fraction', 'age']]
y = data['DEATH_EVENT']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [91]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn import tree

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
import tensorflow as tf

# Criando modelos

Antes de mais nada, vamos esclarescer algumas decisões tomadas para decidirmos o melhor modelo:

    • Iremos prestar atenção principalmente para o recall do modelo, pois ele tenta analisar aqueles que o modelo realmente acertou (ideal para doenças pois analisa principalmente VERDADEIROS POSITIVOS)

LogisticRegression

In [92]:
clf = LogisticRegression(random_state=0).fit(X_train, y_train)
prev = clf.predict(X_test)

print(f'Accuracy: {accuracy_score(y_test, prev)}')
print(f'Recall: {recall_score(y_test, prev)}')
print(f'F1: {f1_score(y_test, prev)}')
print(confusion_matrix(y_test, prev))


Accuracy: 0.8080808080808081
Recall: 0.6428571428571429
F1: 0.7397260273972603
[[53  4]
 [15 27]]


DecisionTree

In [93]:
clf = tree.DecisionTreeClassifier(random_state=0).fit(X_train, y_train)
prev = clf.predict(X_test)

print(f'Accuracy: {accuracy_score(y_test, prev)}')
print(f'Recall: {recall_score(y_test, prev)}')
print(f'F1: {f1_score(y_test, prev)}')
print(confusion_matrix(y_test, prev))


Accuracy: 0.7070707070707071
Recall: 0.5476190476190477
F1: 0.6133333333333334
[[47 10]
 [19 23]]


KNN

In [94]:
neigh = KNeighborsClassifier(n_neighbors=2).fit(X_train, y_train)
prev = neigh.predict(X_test)

print(f'Accuracy: {accuracy_score(y_test, prev)}')
print(f'Recall: {recall_score(y_test, prev)}')
print(f'F1: {f1_score(y_test, prev)}')
print(confusion_matrix(y_test, prev))

Accuracy: 0.7272727272727273
Recall: 0.42857142857142855
F1: 0.5714285714285714
[[54  3]
 [24 18]]


SVM

In [95]:
model = make_pipeline(StandardScaler(), SVC(gamma='auto')).fit(X_train, y_train)
prev = model.predict(X_test)

print(f'Accuracy: {accuracy_score(y_test, prev)}')
print(f'Recall: {recall_score(y_test, prev)}')
print(f'F1: {f1_score(y_test, prev)}')
print(confusion_matrix(y_test, prev))

Accuracy: 0.797979797979798
Recall: 0.6666666666666666
F1: 0.7368421052631577
[[51  6]
 [14 28]]


RandomForest

In [96]:
clf = RandomForestClassifier(max_depth=2, random_state=0).fit(X_train, y_train)
prev = clf.predict(X_test)

print(f'Accuracy: {accuracy_score(y_test, prev)}')
print(f'Recall: {recall_score(y_test, prev)}')
print(f'F1: {f1_score(y_test, prev)}')
print(confusion_matrix(y_test, prev))

Accuracy: 0.7474747474747475
Recall: 0.47619047619047616
F1: 0.6153846153846153
[[54  3]
 [22 20]]


GradientBoosting

In [97]:
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0).fit(X_train, y_train)
prev = clf.predict(X_test)

print(f'Accuracy: {accuracy_score(y_test, prev)}')
print(f'Recall: {recall_score(y_test, prev)}')
print(f'F1: {f1_score(y_test, prev)}')
print(confusion_matrix(y_test, prev))

Accuracy: 0.7676767676767676
Recall: 0.6428571428571429
F1: 0.7012987012987013
[[49  8]
 [15 27]]


Keras

In [99]:
classificador = Sequential()
classificador.add(Dense(units=3, activation='relu', input_dim=4))
classificador.add(Dense(units=3, activation='relu'))
classificador.add(Dense(units=1, activation='sigmoid'))
classificador.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy', tf.keras.metrics.Recall()])

classificador.fit(X_train, y_train, batch_size=10, epochs=400)

Epoch 1/400
20/20 [==============================] - 1s 1ms/step - loss: 1.2360 - accuracy: 0.7850 - recall_10: 0.2222 
Epoch 2/400
20/20 [==============================] - 0s 2ms/step - loss: 1.0491 - accuracy: 0.7950 - recall_10: 0.2778
Epoch 3/400
20/20 [==============================] - 0s 2ms/step - loss: 0.8904 - accuracy: 0.8100 - recall_10: 0.3333
Epoch 4/400
20/20 [==============================] - 0s 2ms/step - loss: 0.7611 - accuracy: 0.8200 - recall_10: 0.3704
Epoch 5/400
20/20 [==============================] - 0s 2ms/step - loss: 0.6545 - accuracy: 0.8100 - recall_10: 0.3704
Epoch 6/400
20/20 [==============================] - 0s 2ms/step - loss: 0.5692 - accuracy: 0.8400 - recall_10: 0.4815
Epoch 7/400
20/20 [==============================] - 0s 1ms/step - loss: 0.5077 - accuracy: 0.8550 - recall_10: 0.5370
Epoch 8/400
20/20 [==============================] - 0s 1ms/step - loss: 0.4728 - accuracy: 0.8650 - recall_10: 0.5741
Epoch 9/400
20/20 [============================

In [ ]:
prev = classificador.predict(X_test)
prev = (prev > 0.6)
print(f'Accuracy: {accuracy_score(y_test, prev)}')
print(f'Recall: {recall_score(y_test, prev)}')
print(f'F1: {f1_score(y_test, prev)}')
print(confusion_matrix(y_test, prev))

4/4 [==============================] - 0s 1ms/step
Accuracy: 0.7474747474747475
Recall: 0.42857142857142855
F1: 0.5901639344262295
[[56  1]
 [24 18]]


# Melhorando o melhor modelo

O melhor modelo encontrado foi o SVC:

In [100]:
model = make_pipeline(StandardScaler(), SVC(gamma='auto')).fit(X_train, y_train)
prev = model.predict(X_test)

print(f'Accuracy: {accuracy_score(y_test, prev)}')
print(f'Recall: {recall_score(y_test, prev)}')
print(f'F1: {f1_score(y_test, prev)}')
print(confusion_matrix(y_test, prev))

Accuracy: 0.797979797979798
Recall: 0.6666666666666666
F1: 0.7368421052631577
[[51  6]
 [14 28]]
